name: SnarkyJS-API-Reference
on: workflow_dispatch

jobs:
  update-snarkyjs-api-reference:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Checkout Docs repo
        uses: actions/checkout@v3
        with:
          path: docs

      - name: Checkout SnarkyJS repo
        uses: actions/checkout@v3
        with:
          repository: o1-labs/snarkyjs
          path: snarkyjs
          ref: main

      - name: Build API reference docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Install dependencies and build SnarkyJS
          cd snarkyjs && npm ci && npm run build
          cd src/mina-signer && npm ci && npm run build && cd ../../

          # Install markdown-plugin for typedoc and build the SnarkyJS API reference
          npm install typedoc-plugin-markdown
          npx typedoc --readme none --name SnarkyJS --plugin typedoc-plugin-markdown --out snarkyjs-reference src/index.ts --hideBreadcrumbs true
          rm snarkyjs-reference/.nojekyll

          # Install dependencies for Docs repo
          cd ../docs/ && npm ci

          # Remove the old API reference and copy the newly generated reference
          rm -rf docs/zkapps/snarkyjs-reference && cp -rv ../snarkyjs/snarkyjs-reference docs/zkapps/snarkyjs-reference

          # Update with new enteries and format sidebars.js
          node update-sidebars-snarkyjs-api.js && npx prettier --config .prettierrc --write sidebars.js

          # Configure git and push
          BRANCH_NAME=docs/snarkyjs-api-reference-$(git --git-dir ../snarkyjs/.git rev-parse --short HEAD)
          git config user.name github-actions
          git config user.email github-actions@github.com
          git switch -c $BRANCH_NAME
          git add docs/zkapps/snarkyjs-reference
          git add sidebars.js
          git commit -m "Build and publish new SnarkyJS API reference docs"

          # Use Github CLI to create a PR
          git push --set-upstream origin $BRANCH_NAME
          gh pr create -B main -H $BRANCH_NAME --title "Build and publish new SnarkyJS API reference docs" --body ""
